[ChangePasswordError]
description = "Ошибка изменения пароля"
hash = "sha1-881dac4ab4fd8564ce9b9fbd95711ee5947bb50a"
other = "Ошибка изменения пароля"

[ChangePasswordErrorMsg]
description = "Не удалось изменить пароль"
hash = "sha1-881937f57a82fba05f0fb712f57eb038e52aba75"
other = "Не удалось изменить пароль"

[ChangePasswordOK]
description = "Смена пароля завершена"
hash = "sha1-d08b0b29f7ee8555f866a7b1386356c5f2e10d6a"
other = "Смена пароля завершена"

[ChangePasswordOKMsg]
description = "Смена пароля выполнена успешно"
hash = "sha1-7ce0180679f8a61780ab6d2a2829ad89733b6044"
other = "Смена пароля выполнена успешно"

[UserAuthError]
description = "Ошибка проверка подлинности пользователя с помощью текущего пароля"
hash = "sha1-e2e4289ce28ef7e4c379e62ffe90e2715979bcfe"
other = "Ошибка аутентификации"

[ValidationError]
description = "Ошибка валидации запроса"
hash = "sha1-d14408e82fcf0ede77881743249433ddb37df0ef"
other = "Ошибка валидации запроса"

[ValidationInternalErrNotEnoughCapitalLetters]
description = "Валидация. Значение должно содержать не менее {{.Digit}} заглавной буквы"
few = "Значение должно содержать не менее {{.Digit}} заглавных букв"
hash = "sha1-5cbe2b06330f0c0a32cf131d89981a4ed234d25e"
many = "Значение должно содержать не менее {{.Digit}} заглавных букв"
one = "Значение должно содержать не менее {{.Digit}} заглавной буквы"
other = "Значение должно содержать не менее {{.Digit}} заглавных букв"

[ValidationInternalErrNotEnoughDigits]
description = "Валидация. Значение должно содержать не менее {{.Digit}} цифры"
few = "Значение должно содержать не менее {{.Digit}} цифры"
hash = "sha1-16e92d42d270dbd914f94a59266d98f73f9f908d"
many = "Значение должно содержать не менее {{.Digit}} цифры"
one = "Значение должно содержать не менее {{.Digit}} цифру"
other = "Значение должно содержать не менее {{.Digit}} цифры"

[ValidationInternalErrNotString]
description = "Валидация. Значение должно быть строкой"
hash = "sha1-ee1cba1a848851ef22d96d901f42fb691fb10293"
other = "Значение должно быть строкой"

[validation_is_alphanumeric]
description = "Валидация. Значение должно содержать цифры и буквы латинского алфавита"
hash = "sha1-fafe365fbd5965f8530f57120f71b4c1330bae75"
other = "Значение должно содержать цифры и буквы латинского алфавита"

[validation_length_out_of_range]
description = "Валидация. Длина значения должна быть между {{.min}} and {{.max}}"
hash = "sha1-36715ab1494acf4cf0287b8f070fa2381fc25720"
other = "Значение должно иметь длину между {{.Min}} and {{.Max}}"

[validation_required]
description = "Валидация. Значение должно быть указано"
hash = "sha1-10e40e03fbaa975727791161580f3d9007b63cbe"
other = "Значение должно быть указано"
