version: '3.9'


services:

  registry:
    image: registry:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: any
        max_attempts: 20
        window: 10s
        delay: 3s
      resources:
        limits:
          cpus: "2"
          memory: "0.5G"
        reservations:
          cpus: "0.5"
          memory: "0.2G"
