version: '3.9'


services:

  static-rust:
    image: ${static_rust_image:-test-static-rust:latest}
    environment:
      - PORT=${STATIC_RUST_PORT:-4000}
    ports:
      - target: ${STATIC_RUST_PORT:-4000}
        published: 82
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: any
        max_attempts: 20
        window: 10s
        delay: 3s
      resources:
        limits:
          cpus: "2"
          memory: "0.5G"
        reservations:
          cpus: "0.5"
          memory: "0.2G"

  static:
    image: ${static_image:-127.0.0.1:5000/test-static:latest}
    environment:
      - PORT=${STATIC_PORT:-3000}
    ports:
      - target: ${STATIC_PORT:-3000}
        published: 81
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 2
        delay: 3s
        failure_action: rollback
        # order: "start-first"
      rollback_config:
        parallelism: 1
        delay: 1s
        failure_action: pause
      restart_policy:
        condition: any
        max_attempts: 20
        window: 10s
        delay: 3s
      resources:
        limits:
          cpus: "2"
          memory: "0.5G"
        reservations:
          cpus: "0.5"
          memory: "0.2G"

  nginx:
    image: ${nginx_image:-nginx:1.19}
    volumes:
      - type: bind
        source: ../cmd/static/dist/spa
        target: /usr/share/nginx/html
        read_only: true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: any
        max_attempts: 20
        window: 10s
        delay: 3s
      resources:
        limits:
          cpus: "2"
          memory: "0.5G"
        reservations:
          cpus: "0.5"
          memory: "0.2G"

